# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Vivado/Tetris/Tetris.cache/wt [current_project]
set_property parent.project_path C:/Vivado/Tetris/Tetris.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/vga.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/clk_unit.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/Tetris_Datapath.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/game_control_unit.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/key.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/vag_top.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/merge.v
  C:/Vivado/Tetris/Tetris.srcs/sources_1/imports/Tetris_Zedboard/tetris.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Vivado/Tetris/Tetris.srcs/constrs_1/new/tetris_basys3.xdc
set_property used_in_implementation false [get_files C:/Vivado/Tetris/Tetris.srcs/constrs_1/new/tetris_basys3.xdc]


synth_design -top tetris -part xc7a35tcpg236-1


write_checkpoint -force -noxdef tetris.dcp

catch { report_utilization -file tetris_utilization_synth.rpt -pb tetris_utilization_synth.pb }
