# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/yafpgatetris/fpgatetris/fpgatetris.srcs/sources_1/ip/string_rom_gameover/string_rom_gameover.xci
# IP: The module: 'string_rom_gameover' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/yafpgatetris/fpgatetris/fpgatetris.srcs/sources_1/ip/string_rom_gameover/string_rom_gameover_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'string_rom_gameover'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/yafpgatetris/fpgatetris/fpgatetris.srcs/sources_1/ip/string_rom_gameover/string_rom_gameover.xci
# IP: The module: 'string_rom_gameover' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/yafpgatetris/fpgatetris/fpgatetris.srcs/sources_1/ip/string_rom_gameover/string_rom_gameover_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'string_rom_gameover'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
