# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/head.coe
add_files C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/gameover.coe
add_files C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/font.coe
add_files C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/headV2.coe
read_verilog C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/defs.vh
read_mem {
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/font.mif
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/head.mif
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/game_over.mif
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/bin_2_bcd.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/check_move.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/draw_big_string_gameover.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/draw_big_string_head.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/draw_field.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/draw_field_helper.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/draw_strings.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/draw_tetris.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/gen_next_block.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/gen_sys_event.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/main_game_logic.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/tetris_stat.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/user_input.sv
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/new/top.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/ps2_keyboard/Altera_UP_PS2_Command_Out.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/ps2_keyboard/Altera_UP_PS2_Data_In.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/ps2_keyboard/PS2_Controller.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/asfifo/async_fifo.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/asfifo/fifo_2mem.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/asfifo/rptr_empty.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/asfifo/sync_r2w.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/asfifo/sync_w2r.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/vga/vga_time_generator.v
  C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/import/tetris/rtl/asfifo/wptr_full.v
}
read_ip -quiet C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/string_rom/string_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/string_rom/string_rom_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/string_rom_head/string_rom_head.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/string_rom_head/string_rom_head_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/string_rom_gameover/string_rom_gameover.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/string_rom_gameover/string_rom_gameover_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/yafpgatetris/fpgatetrisV3/fpgatetris.srcs/constrs_1/new/pin.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
