set_property IOSTANDARD LVCMOS33 [get_ports {OutRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutRed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OutBlue[0]}]
set_property PACKAGE_PIN N19 [get_ports {OutRed[3]}]
set_property PACKAGE_PIN J19 [get_ports {OutRed[2]}]
set_property PACKAGE_PIN H19 [get_ports {OutRed[1]}]
set_property PACKAGE_PIN G19 [get_ports {OutRed[0]}]
set_property PACKAGE_PIN D17 [get_ports {OutGreen[3]}]
set_property PACKAGE_PIN G17 [get_ports {OutGreen[2]}]
set_property PACKAGE_PIN H17 [get_ports {OutGreen[1]}]
set_property PACKAGE_PIN J17 [get_ports {OutGreen[0]}]
set_property PACKAGE_PIN J18 [get_ports {OutBlue[3]}]
set_property PACKAGE_PIN K18 [get_ports {OutBlue[2]}]
set_property PACKAGE_PIN L18 [get_ports {OutBlue[1]}]
set_property PACKAGE_PIN N18 [get_ports {OutBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_r]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_r]
set_property PACKAGE_PIN R19 [get_ports vsync_r]
set_property PACKAGE_PIN P19 [get_ports hsync_r]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports UP_KEY]
set_property PACKAGE_PIN T18 [get_ports UP_KEY]
set_property IOSTANDARD LVCMOS33 [get_ports LEFT_KEY]
set_property PACKAGE_PIN W19 [get_ports LEFT_KEY]
set_property IOSTANDARD LVCMOS33 [get_ports RIGHT_KEY]
set_property PACKAGE_PIN T17 [get_ports RIGHT_KEY]
set_property IOSTANDARD LVCMOS33 [get_ports DOWN_KEY]
set_property PACKAGE_PIN U17 [get_ports DOWN_KEY]

set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property PACKAGE_PIN V17 [get_ports start]

