# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Downloads/fpga_snake-master/fpga_snake/fpga_snake.srcs/sources_1/ip/font_romv1/font_romv1.xci
# IP: The module: 'font_romv1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Downloads/fpga_snake-master/fpga_snake/fpga_snake.srcs/sources_1/ip/font_romv1/font_romv1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'font_romv1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Downloads/fpga_snake-master/fpga_snake/fpga_snake.srcs/sources_1/ip/font_romv1/font_romv1.xci
# IP: The module: 'font_romv1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Downloads/fpga_snake-master/fpga_snake/fpga_snake.srcs/sources_1/ip/font_romv1/font_romv1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'font_romv1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
